import builtins from "builtin-modules"

import esbuild from "esbuild"

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const isProd = process.env.npm_lifecycle_event?.split(":")[1] === "prod"

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins
    ],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: isProd ? false : "inline",
	treeShaking: true,
	outfile: isProd ? "dist/main.js" :"build/main.js",
})

if (isProd) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch(() => {})
}